name: bielik
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - keyring
  - pyside6
  - openai
  - markdown
  - langchain
  - langchain-openai
  - langchain-community
  - duckduckgo-search
  - pypdf
  - python-docx
  - pypandoc
  - pip:
    - --extra-index-url https://pypi.org/simple
